### ISSUE TITLE
error End-chest

### ISSUE THREAD

**Issue by PuzzleChannel** [tomalbrc/camera-obscura#2]
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]: java.lang.IllegalArgumentException: Cannot get property class_2754{name=type, clazz=class net.minecraft.class_2745, values=[SINGLE, LEFT, RIGHT]} as it does not exist in Block{minecraft:ender_chest}
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at net.minecraft.class_2688.method_11654(class_2688.java:97)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at de.tomalbrc.cameraobscura.util.model.ChestModel.get(ChestModel.java:28)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at de.tomalbrc.cameraobscura.util.BuiltinModels.chestModel(BuiltinModels.java:63)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at de.tomalbrc.cameraobscura.render.Raytracer.colorFromRaycast(Raytracer.java:142)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at de.tomalbrc.cameraobscura.render.Raytracer.traceSingle(Raytracer.java:99)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at de.tomalbrc.cameraobscura.render.Raytracer.trace(Raytracer.java:64)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at de.tomalbrc.cameraobscura.render.renderer.CanvasImageRenderer.render(CanvasImageRenderer.java:28)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at de.tomalbrc.cameraobscura.command.CameraCommand.lambda$createMap$6(CameraCommand.java:153)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[14:45:32] [ForkJoinPool.commonPool-worker-8/INFO]: [STDERR]:   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

**Comment by tomalbrc** [comment]
Thanks for reporting this, will be fixed with the next version

**Comment by tomalbrc** [comment]
Fixed in 1.2.0
